# Generated by Django 2.2.4 on 2019-09-04 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=500)),
                ('watch_count', models.IntegerField(default=0)),
                ('averagerate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='M', max_length=10)),
                ('age', models.IntegerField(default=25)),
                ('occupation', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('Timestamp', models.IntegerField()),
                ('MovieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_movie', to='api.Movie')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_rate', to='api.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='score_users',
            field=models.ManyToManyField(related_name='score_movies', through='api.Rate', to='api.Profile'),
        ),
    ]
