# Generated by Django 2.2.4 on 2019-09-25 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_component', models.IntegerField(default=0)),
                ('way', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='casting',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscription',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 13, 47, 43, 630123)),
        ),
        migrations.CreateModel(
            name='User_Cluster_Kmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K3', models.IntegerField(default=0)),
                ('K4', models.IntegerField(default=0)),
                ('K5', models.IntegerField(default=0)),
                ('K6', models.IntegerField(default=0)),
                ('K7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_Kmeans', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cluster_Hmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H3', models.IntegerField(default=0)),
                ('H4', models.IntegerField(default=0)),
                ('H5', models.IntegerField(default=0)),
                ('H6', models.IntegerField(default=0)),
                ('H7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_Hmeans', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cluster_EM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM3', models.IntegerField(default=0)),
                ('EM4', models.IntegerField(default=0)),
                ('EM5', models.IntegerField(default=0)),
                ('EM6', models.IntegerField(default=0)),
                ('EM7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_EM', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
                ('request_day', models.DateTimeField(auto_now_add=True)),
                ('apply_day', models.DateTimeField(auto_now=True)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sub', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_Kmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K3', models.IntegerField(default=0)),
                ('K4', models.IntegerField(default=0)),
                ('K5', models.IntegerField(default=0)),
                ('K6', models.IntegerField(default=0)),
                ('K7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_Kmeans', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_Hmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H3', models.IntegerField(default=0)),
                ('H4', models.IntegerField(default=0)),
                ('H5', models.IntegerField(default=0)),
                ('H6', models.IntegerField(default=0)),
                ('H7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_Hmeans', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_EM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM3', models.IntegerField(default=0)),
                ('EM4', models.IntegerField(default=0)),
                ('EM5', models.IntegerField(default=0)),
                ('EM6', models.IntegerField(default=0)),
                ('EM7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_EM', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie1', to='api.Movie')),
                ('Movie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie10', to='api.Movie')),
                ('Movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie2', to='api.Movie')),
                ('Movie3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie3', to='api.Movie')),
                ('Movie4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie4', to='api.Movie')),
                ('Movie5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie5', to='api.Movie')),
                ('Movie6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie6', to='api.Movie')),
                ('Movie7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie7', to='api.Movie')),
                ('Movie8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie8', to='api.Movie')),
                ('Movie9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie9', to='api.Movie')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_set', to='api.Profile')),
            ],
        ),
    ]
