# Generated by Django 2.2.4 on 2019-09-24 07:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 13, 47, 43, 630123)),
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie1', to='api.Movie')),
                ('Movie10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie10', to='api.Movie')),
                ('Movie2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie2', to='api.Movie')),
                ('Movie3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie3', to='api.Movie')),
                ('Movie4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie4', to='api.Movie')),
                ('Movie5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie5', to='api.Movie')),
                ('Movie6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie6', to='api.Movie')),
                ('Movie7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie7', to='api.Movie')),
                ('Movie8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie8', to='api.Movie')),
                ('Movie9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie9', to='api.Movie')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_set', to='api.Profile')),
            ],
        ),
    ]
