# Generated by Django 2.2.4 on 2019-09-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_component', models.IntegerField(default=0)),
                ('way', models.CharField(max_length=50)),
            ],
        ),
    ]
