# Generated by Django 2.2.4 on 2019-09-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Cluster_Kmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K3', models.IntegerField(default=0)),
                ('K4', models.IntegerField(default=0)),
                ('K5', models.IntegerField(default=0)),
                ('K6', models.IntegerField(default=0)),
                ('K7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_Kmeans', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cluster_Hmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H3', models.IntegerField(default=0)),
                ('H4', models.IntegerField(default=0)),
                ('H5', models.IntegerField(default=0)),
                ('H6', models.IntegerField(default=0)),
                ('H7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_Hmeans', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Cluster_EM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM3', models.IntegerField(default=0)),
                ('EM4', models.IntegerField(default=0)),
                ('EM5', models.IntegerField(default=0)),
                ('EM6', models.IntegerField(default=0)),
                ('EM7', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cluster_EM', to='api.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_Kmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('K3', models.IntegerField(default=0)),
                ('K4', models.IntegerField(default=0)),
                ('K5', models.IntegerField(default=0)),
                ('K6', models.IntegerField(default=0)),
                ('K7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_Kmeans', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_Hmeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('H3', models.IntegerField(default=0)),
                ('H4', models.IntegerField(default=0)),
                ('H5', models.IntegerField(default=0)),
                ('H6', models.IntegerField(default=0)),
                ('H7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_Hmeans', to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Cluster_EM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EM3', models.IntegerField(default=0)),
                ('EM4', models.IntegerField(default=0)),
                ('EM5', models.IntegerField(default=0)),
                ('EM6', models.IntegerField(default=0)),
                ('EM7', models.IntegerField(default=0)),
                ('MovieId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cluster_EM', to='api.Movie')),
            ],
        ),
    ]
