# Generated by Django 2.2.4 on 2019-09-11 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190910_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 15, 14, 9, 880322)),
        ),
    ]
