# Generated by Django 2.2.4 on 2019-09-10 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190910_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 10, 5, 29, 124492)),
        ),
        migrations.CreateModel(
            name='Subscription_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.IntegerField(default=0)),
                ('approval', models.BooleanField(default=False)),
                ('request_day', models.DateTimeField(auto_now_add=True)),
                ('apply_day', models.DateTimeField(auto_now=True)),
                ('Profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sub', to='api.Profile')),
            ],
        ),
    ]
