# Generated by Django 2.2.4 on 2019-09-11 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190910_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscription',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 13, 52, 56, 781676)),
        ),
    ]
